DPE-7166: Add spread tests and backward compatibility with legacy OCI (#2)
* DPE-7166: Add spread tests and backward compatibility with legacy OCI

* add backward compatibility with legacy OCI and official DockerHub image
* add spread-based test using `rockctraft test`
* add `rockctraft test` to CI
* use Lint CI from data-platform-workflows
* update readme with more examples

* Add arm tests + bump data-platform-workflows

* Update README.md

* Fix shellcheck actionlint warnings

* Fix shellcheck actionlint warnings #2

* Fix shellcheck actionlint warnings #3

* Increase timeout on ARM (slow runners)

* DPE-7166: Removed --raw-output from oci-factory release

It is no longer necessary as we have removed quotes from version field
of rockcraft.yaml, discussed this with Rock team, it should be safe.

* DPE-7166: Cast yq type after removing quotes from rockcraft.yaml

Otherwise:

> yq '.version | split(".")[0]' rockcraft.yaml
Error: cannot split !!float, can only split strings